# SPDX-FileCopyrightText: 2026 The Attestplane Authors
# SPDX-License-Identifier: Apache-2.0
"""Attestplane — verifiable audit substrate for AI agents.

Designed toward EU AI Act Article 12 auditability. Apache-2.0 licensed. See:
- https://github.com/attestplane/attestplane
- docs/adr/0002-substrate-data-model-and-hash-chain-v0.md
"""

from attestplane.adapter_conformance import (
    AdapterCaseResult,
    AdapterConformanceError,
    AdapterConformanceReport,
    replay_fixture,
)
from attestplane.adapters import (
    AdapterError,
    AdapterTranslationError,
    GenericRuntimeAdapter,
    LangFuseAdapter,
    LangFuseObservation,
    LangSmithAdapter,
    LangSmithRun,
    RuntimeEvent,
)
from attestplane.anchoring import (
    ANCHOR_SCHEMA_VERSION,
    AnchorError,
    AnchorPolicy,
    AnchorRecord,
    AnchorVerificationError,
    AnchorVerificationResult,
    MockTSAProvider,
    MultiTSAProvider,
    SingleAnchorResult,
    TimestampRequest,
    TSAProvider,
    TSAUnavailableError,
    verify_chain_with_anchors,
)
from attestplane.canonical import CanonicalizationError, canonicalize
from attestplane.canonical_text import (
    CanonicalTextError,
    canonicalize_text,
    text_hash,
    text_hash_hex,
)
from attestplane.event_payloads import (
    FORBIDDEN_PAYLOAD_FIELDS,
    LeaseLifecycle,
    LeaseLifecycleEventPayload,
    PolicyCheckEventPayload,
    PolicyDecision,
    PolicyEffect,
    ReplayEventPayload,
    validate_lease_lifecycle_event_payload,
    validate_policy_check_event_payload,
    validate_replay_event_payload,
)
from attestplane.event_types import (
    ALL_EVENT_TYPES_V1,
    BUDGET_EVENT,
    EVAL_EVENT,
    EVIDENCE_TAXONOMY_VERSION,
    GATEWAY_DECISION_EVENT,
    HUMAN_APPROVAL_EVENT,
    LEASE_LIFECYCLE_EVENT,
    POLICY_CHECK_EVENT,
    ROUTING_EVENT,
    RUNTIME_LIFECYCLE_EVENT,
    SETTLEMENT_EVENT,
    STATE_TRANSITION_EVENT,
    TOOL_CALL_EVENT,
    WORKER_ASSIGNMENT_EVENT,
    is_known_v1_event_type,
)
from attestplane.intoto import (
    DSSE_PAYLOAD_TYPE,
    PREDICATE_TYPE_V1,
    STATEMENT_TYPE,
    IntotoError,
    dsse_envelope_to_statement,
    proof_bundle_to_in_toto_statement,
    statement_to_dsse_envelope,
)
from attestplane.obligations import (
    ObligationEntry,
    ObligationRegistryError,
    Registry,
    load_all_registries,
    load_dora_article_8,
    load_eu_ai_act_article_12,
)
from attestplane.proof_bundle import (
    DEFAULT_FORBIDDEN_FIELDS,
    FrameworkMapping,
    ProofBundleBuilder,
    build_auditor_export,
    bundle_to_dsse_envelope,
    bundle_to_in_toto_statement,
)
from attestplane.reason_codes import (
    ALL_REASON_CODES_V1,
    REASON_CODE_DESCRIPTIONS,
    REASON_CODE_SCHEMA_VERSION,
    ReasonCodeV1,
    is_known_reason_code,
    reason_code_matches_format,
)
from attestplane.replay_verifier import (
    ReplayCoverage,
    ReplayManifest,
    ReplayVerificationResult,
    verify_replay_manifest,
)
from attestplane.retention import (
    RETENTION_PROOF_SCHEMA_VERSION,
    RetentionProofVerificationResult,
    build_deletion_proof,
    build_retention_marker,
    validate_retention_proof,
    verify_retention_proofs,
)
from attestplane.settlement_verifier import (
    SettlementPreconditionClaim,
    SettlementVerificationResult,
    check_settlement_precondition,
)

# Event signing primitives (T1+T2 of ADR-0005 plan).
# Guarded so substrate-only installs without [signing] extras don't fail.
try:
    from attestplane.signing import (  # noqa: F401
        SIGNATURE_SCHEMA_VERSION,
        EnvKeyProvider,
        FileKeyProvider,
        InMemoryKeyProvider,
        KeyBoundaryError,
        KeyProvider,
        KeyProviderError,
        MultiSignerProvider,
        SignatureMode,
        SignaturePolicy,
        SignatureRecord,
        SignatureVerificationError,
        SigningError,
        SigningMaterial,
        derive_key_id,
    )

    _SIGNING_AVAILABLE = True
except ImportError:  # pragma: no cover
    _SIGNING_AVAILABLE = False
from attestplane.hashchain import (
    GENESIS_HASH,
    SCHEMA_VERSION,
    VerificationResult,
    chain_extend,
    genesis_head,
    hash_event,
    verify_chain,
)
from attestplane.storage import (
    AbstractStorageBackend,
    JsonlStorageBackend,
    StorageError,
    StorageReadError,
    StorageWriteError,
)
from attestplane.substrate import AttestSubstrate
from attestplane.types import (
    AuditEvent,
    ChainedEvent,
    ChainHead,
    EventDraft,
    SubjectRef,
)
from attestplane.verifier import (
    BundleSchemaError,
    BundleVerificationError,
    BundleVerificationResult,
    verify_proof_bundle,
    verify_proof_bundle_file,
)
from attestplane.verify_errors import (
    ALL_VERIFY_ERROR_CODES_V1,
    VERIFY_ERROR_DESCRIPTIONS,
    VERIFY_ERROR_SCHEMA_VERSION,
    VerifyErrorCode,
    is_known_verify_error_code,
)

__version__ = "1.4.3"

__all__ = [
    "ALL_EVENT_TYPES_V1",
    "BUDGET_EVENT",
    "EVAL_EVENT",
    "EVIDENCE_TAXONOMY_VERSION",
    "GATEWAY_DECISION_EVENT",
    "GENESIS_HASH",
    "HUMAN_APPROVAL_EVENT",
    "LEASE_LIFECYCLE_EVENT",
    "POLICY_CHECK_EVENT",
    "ROUTING_EVENT",
    "RUNTIME_LIFECYCLE_EVENT",
    "SCHEMA_VERSION",
    "SETTLEMENT_EVENT",
    "STATE_TRANSITION_EVENT",
    "TOOL_CALL_EVENT",
    "WORKER_ASSIGNMENT_EVENT",
    "AdapterCaseResult",
    "AdapterConformanceError",
    "AdapterConformanceReport",
    "AdapterError",
    "AdapterTranslationError",
    "AttestSubstrate",
    "AuditEvent",
    "CanonicalTextError",
    "CanonicalizationError",
    "DSSE_PAYLOAD_TYPE",
    "IntotoError",
    "PREDICATE_TYPE_V1",
    "STATEMENT_TYPE",
    "ChainHead",
    "ChainedEvent",
    "EventDraft",
    "ANCHOR_SCHEMA_VERSION",
    "AbstractStorageBackend",
    "AnchorError",
    "AnchorPolicy",
    "AnchorRecord",
    "AnchorVerificationError",
    "AnchorVerificationResult",
    "BundleSchemaError",
    "BundleVerificationError",
    "BundleVerificationResult",
    "DEFAULT_FORBIDDEN_FIELDS",
    "FORBIDDEN_PAYLOAD_FIELDS",
    "FrameworkMapping",
    "GenericRuntimeAdapter",
    "LangFuseAdapter",
    "LangFuseObservation",
    "LangSmithAdapter",
    "LangSmithRun",
    "LeaseLifecycle",
    "LeaseLifecycleEventPayload",
    "PolicyCheckEventPayload",
    "PolicyDecision",
    "PolicyEffect",
    "ReplayCoverage",
    "ReplayEventPayload",
    "ReplayManifest",
    "ReplayVerificationResult",
    "SettlementPreconditionClaim",
    "SettlementVerificationResult",
    "ALL_REASON_CODES_V1",
    "ALL_VERIFY_ERROR_CODES_V1",
    "REASON_CODE_DESCRIPTIONS",
    "REASON_CODE_SCHEMA_VERSION",
    "RETENTION_PROOF_SCHEMA_VERSION",
    "ReasonCodeV1",
    "RetentionProofVerificationResult",
    "VERIFY_ERROR_DESCRIPTIONS",
    "VERIFY_ERROR_SCHEMA_VERSION",
    "VerifyErrorCode",
    "is_known_reason_code",
    "is_known_verify_error_code",
    "reason_code_matches_format",
    "MockTSAProvider",
    "MultiTSAProvider",
    "JsonlStorageBackend",
    "ObligationEntry",
    "ObligationRegistryError",
    "ProofBundleBuilder",
    "Registry",
    "RuntimeEvent",
    "SingleAnchorResult",
    "StorageError",
    "StorageReadError",
    "StorageWriteError",
    "SubjectRef",
    "TSAProvider",
    "TSAUnavailableError",
    "TimestampRequest",
    "VerificationResult",
    "__version__",
    "canonicalize",
    "chain_extend",
    "genesis_head",
    "hash_event",
    "build_auditor_export",
    "build_deletion_proof",
    "build_retention_marker",
    "bundle_to_dsse_envelope",
    "bundle_to_in_toto_statement",
    "canonicalize_text",
    "dsse_envelope_to_statement",
    "is_known_v1_event_type",
    "load_all_registries",
    "load_dora_article_8",
    "load_eu_ai_act_article_12",
    "proof_bundle_to_in_toto_statement",
    "statement_to_dsse_envelope",
    "text_hash",
    "text_hash_hex",
    "validate_lease_lifecycle_event_payload",
    "validate_policy_check_event_payload",
    "validate_replay_event_payload",
    "validate_retention_proof",
    "verify_replay_manifest",
    "verify_retention_proofs",
    "check_settlement_precondition",
    "replay_fixture",
    "verify_chain",
    "verify_chain_with_anchors",
    "verify_proof_bundle",
    "verify_proof_bundle_file",
]

if _SIGNING_AVAILABLE:
    __all__.extend([
        "SIGNATURE_SCHEMA_VERSION",
        "EnvKeyProvider",
        "FileKeyProvider",
        "InMemoryKeyProvider",
        "KeyBoundaryError",
        "KeyProvider",
        "KeyProviderError",
        "MultiSignerProvider",
        "SignatureMode",
        "SignatureRecord",
        "SignatureVerificationError",
        "SignaturePolicy",
        "SigningError",
        "SigningMaterial",
        "derive_key_id",
    ])
