# SPDX-FileCopyrightText: 2026 The Attestplane Authors
# SPDX-License-Identifier: Apache-2.0
"""High-level proof-bundle verifier.

Takes a bundle dict (or path to a bundle JSON file), validates against
``schemas/v1/proof_bundle.schema.json``, rehydrates the contained
events, re-walks the chain with :func:`~attestplane.hashchain.verify_chain`,
and returns a :class:`BundleVerificationResult`.

Verifiers are intentionally **pure** with respect to the bundle: they
do not mutate, sign, or anchor. Verification is read-only.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from attestplane.event_types import POLICY_CHECK_EVENT
from attestplane.hashchain import GENESIS_HASH, SCHEMA_VERSION, VerificationResult, head_of, verify_chain
from attestplane.proof_bundle import DEFAULT_FORBIDDEN_FIELDS
from attestplane.storage.jsonl import _deserialize_event as _deserialize_chained_event
from attestplane.types import ChainedEvent


class BundleVerificationError(Exception):
    """Base class for verifier failures that are NOT chain integrity failures.

    Chain-integrity failures are reported via
    :class:`BundleVerificationResult` (``ok=False``); this exception is
    reserved for malformed inputs that prevent verification from running
    at all (bad JSON, schema violation, unreadable file).
    """


class BundleSchemaError(BundleVerificationError):
    """The bundle JSON does not conform to proof_bundle.schema.json."""


@dataclass(frozen=True, slots=True)
class BundleVerificationResult:
    """Outcome of verifying a proof bundle.

    - ``ok=True`` means the embedded chain verifies AND the bundle's own
      ``verification_report.ok`` agreed.
    - ``ok=False`` means EITHER the bundle's report disagrees with our
      independent re-verification, OR our re-verification surfaced a
      chain integrity failure.

    A disagreement between the embedded report and the independent
    re-verification is a strong signal: it means the bundle was either
    generated by a buggy producer or has been tampered with between
    generation and reading.
    """

    ok: bool
    chain_result: VerificationResult
    bundle_reported_ok: bool
    agreement: bool
    """``True`` iff the bundle's embedded report agrees with the independent re-verification."""
    event_count: int
    bundle_version: int
    chain_id: str
    head_hash_hex: str
    metadata_ok: bool
    metadata_reason: str | None
    policy_trace_refs_ok: bool
    policy_trace_refs_reason: str | None

    def short_summary(self) -> str:
        if self.ok:
            return (
                f"OK chain_id={self.chain_id!r} events={self.event_count} "
                f"head={self.head_hash_hex[:16]}…"
            )
        bad = self.chain_result.first_bad_index
        return (
            f"FAIL chain_id={self.chain_id!r} events={self.event_count} "
            f"first_bad_index={bad} reason={self.chain_result.reason!r} "
            f"agreement={self.agreement} metadata_reason={self.metadata_reason!r} "
            f"policy_trace_refs_reason={self.policy_trace_refs_reason!r}"
        )


_REQUIRED_TOP_LEVEL = {
    "bundle_version",
    "chain_metadata",
    "events",
    "verification_report",
    "forbidden_fields",
}
_REQUIRED_CHAIN_METADATA = {
    "chain_id", "schema_version", "genesis_hash_hex",
    "head_hash_hex", "head_seq", "producer_runtime",
}
_REQUIRED_VERIFICATION_REPORT = {
    "ok", "first_bad_index", "reason", "verified_at",
    "verifier_version", "verification_method",
}
_ALLOWED_TOP_LEVEL = _REQUIRED_TOP_LEVEL | {
    "framework_mappings",
    "signature",
    "policy_trace_refs",
    "signatures",
}
_ALLOWED_VERIFICATION_METHODS = {"canonical-bytes-walk", "canonical-bytes-walk+anchor"}
_HEX64 = re.compile(r"^[0-9a-f]{64}$")


def _validate_shape(bundle: Any) -> None:
    """Lightweight schema validation — sufficient to safely rehydrate.

    Intentionally not the full JSON Schema validator. Callers who need
    the full validator can run ``jsonschema.validate(bundle, schema)``
    against ``schemas/v1/proof_bundle.schema.json``; for the verifier
    fast path we only check what we read.
    """
    if not isinstance(bundle, dict):
        raise BundleSchemaError(f"bundle must be a JSON object, got {type(bundle).__name__}")
    unknown = set(bundle) - _ALLOWED_TOP_LEVEL
    if unknown:
        raise BundleSchemaError(f"bundle contains unknown top-level fields: {sorted(unknown)}")
    missing = _REQUIRED_TOP_LEVEL - set(bundle)
    if missing:
        raise BundleSchemaError(f"bundle missing required fields: {sorted(missing)}")
    if bundle["bundle_version"] != 1:
        raise BundleSchemaError(
            f"unsupported bundle_version={bundle['bundle_version']!r}; "
            f"this verifier handles version 1 only"
        )
    if not isinstance(bundle["chain_metadata"], dict):
        raise BundleSchemaError("chain_metadata must be a JSON object")
    missing_cm = _REQUIRED_CHAIN_METADATA - set(bundle["chain_metadata"])
    if missing_cm:
        raise BundleSchemaError(
            f"chain_metadata missing required fields: {sorted(missing_cm)}"
        )
    if not isinstance(bundle["events"], list):
        raise BundleSchemaError("events must be an array")
    if not isinstance(bundle["verification_report"], dict):
        raise BundleSchemaError("verification_report must be a JSON object")
    missing_report = _REQUIRED_VERIFICATION_REPORT - set(bundle["verification_report"])
    if missing_report:
        raise BundleSchemaError(
            f"verification_report missing required fields: {sorted(missing_report)}"
        )
    method = bundle["verification_report"]["verification_method"]
    if method not in _ALLOWED_VERIFICATION_METHODS:
        raise BundleSchemaError(f"unsupported verification_method={method!r}")
    if not isinstance(bundle["forbidden_fields"], list):
        raise BundleSchemaError("forbidden_fields must be an array")
    forbidden = bundle["forbidden_fields"]
    if not all(isinstance(item, str) and item for item in forbidden):
        raise BundleSchemaError("forbidden_fields must contain non-empty strings")
    missing_forbidden = set(DEFAULT_FORBIDDEN_FIELDS) - set(forbidden)
    if missing_forbidden:
        raise BundleSchemaError(
            f"forbidden_fields missing required redaction terms: {sorted(missing_forbidden)}"
        )
    if "framework_mappings" in bundle and not isinstance(bundle["framework_mappings"], list):
        raise BundleSchemaError("framework_mappings must be an array when present")
    if "policy_trace_refs" in bundle and not isinstance(bundle["policy_trace_refs"], list):
        raise BundleSchemaError("policy_trace_refs must be an array when present")


def _rehydrate_events(events_raw: list[dict[str, Any]]) -> list[ChainedEvent]:
    chain: list[ChainedEvent] = []
    for idx, ev_raw in enumerate(events_raw):
        try:
            chain.append(_deserialize_chained_event(ev_raw))
        except (KeyError, ValueError, TypeError) as exc:
            raise BundleSchemaError(
                f"events[{idx}]: malformed event row: {exc}"
            ) from exc
    return chain


def _verify_metadata_closure(
    bundle: dict[str, Any],
    events: list[ChainedEvent],
    chain_result: VerificationResult,
) -> tuple[bool, str | None]:
    metadata = bundle["chain_metadata"]
    report = bundle["verification_report"]
    if metadata["schema_version"] != SCHEMA_VERSION:
        return False, (
            f"chain_metadata.schema_version={metadata['schema_version']!r}; "
            f"this verifier handles {SCHEMA_VERSION}"
        )
    if metadata["genesis_hash_hex"] != GENESIS_HASH.hex():
        return False, "chain_metadata.genesis_hash_hex does not match substrate genesis hash"
    if "evidence_taxonomy_version" in metadata and metadata["evidence_taxonomy_version"] != 1:
        return False, "chain_metadata.evidence_taxonomy_version must be 1 when present"

    head = head_of(events)
    if metadata["head_seq"] != head.seq:
        return False, (
            f"chain_metadata.head_seq={metadata['head_seq']!r} does not match "
            f"computed head seq {head.seq}"
        )
    if metadata["head_hash_hex"] != head.event_hash.hex():
        return False, "chain_metadata.head_hash_hex does not match computed chain head"

    if bool(report["ok"]) != chain_result.ok:
        return False, "verification_report.ok disagrees with recomputed chain result"
    if report["first_bad_index"] != chain_result.first_bad_index:
        return False, "verification_report.first_bad_index disagrees with recomputed chain result"
    if report["reason"] != chain_result.reason:
        return False, "verification_report.reason disagrees with recomputed chain result"
    if chain_result.ok and (report["first_bad_index"] is not None or report["reason"] is not None):
        return False, "verification_report carries failure detail while recomputed chain is ok"
    return True, None


def _verify_policy_trace_refs(bundle: dict[str, Any], events: list[ChainedEvent]) -> tuple[bool, str | None]:
    expected = [
        event.event_hash.hex()
        for event in events
        if event.event.event_type == POLICY_CHECK_EVENT
    ]
    present = "policy_trace_refs" in bundle
    if not expected:
        if not present:
            return True, None
        refs = bundle["policy_trace_refs"]
        if refs == []:
            return False, "policy_trace_refs must be absent, not empty, when no policy_check_event exists"
        return False, "policy_trace_refs present but bundle contains no policy_check_event"

    if not present:
        return False, "policy_trace_refs missing while bundle contains policy_check_event"
    refs = bundle["policy_trace_refs"]
    if not all(isinstance(ref, str) and _HEX64.match(ref) for ref in refs):
        return False, "policy_trace_refs must contain only lowercase 64-hex event hashes"
    if len(refs) != len(set(refs)):
        return False, "policy_trace_refs contains duplicate event hashes"
    actual_event_hashes = {event.event_hash.hex() for event in events}
    dangling = [ref for ref in refs if ref not in actual_event_hashes]
    if dangling:
        return False, f"policy_trace_refs contains dangling refs: {dangling}"
    wrong_type = [
        ref for ref in refs
        if ref in actual_event_hashes and ref not in expected
    ]
    if wrong_type:
        return False, f"policy_trace_refs points at non-policy events: {wrong_type}"
    if refs != expected:
        return False, "policy_trace_refs does not match chain-seq-ordered policy_check_event hashes"
    return True, None


def verify_proof_bundle(bundle: dict[str, Any]) -> BundleVerificationResult:
    """Verify a parsed proof-bundle dict.

    Raises :class:`BundleSchemaError` if the shape is invalid. Otherwise
    returns a :class:`BundleVerificationResult`; ``result.ok`` is
    ``True`` only if the chain re-verifies AND the embedded report
    agreed.
    """
    _validate_shape(bundle)
    events = _rehydrate_events(bundle["events"])
    chain_result = verify_chain(events)
    bundle_reported_ok = bool(bundle["verification_report"]["ok"])
    agreement = bundle_reported_ok == chain_result.ok
    metadata_ok, metadata_reason = _verify_metadata_closure(bundle, events, chain_result)
    policy_ok, policy_reason = _verify_policy_trace_refs(bundle, events)
    return BundleVerificationResult(
        ok=chain_result.ok and agreement and metadata_ok and policy_ok,
        chain_result=chain_result,
        bundle_reported_ok=bundle_reported_ok,
        agreement=agreement,
        event_count=len(events),
        bundle_version=int(bundle["bundle_version"]),
        chain_id=str(bundle["chain_metadata"]["chain_id"]),
        head_hash_hex=str(bundle["chain_metadata"]["head_hash_hex"]),
        metadata_ok=metadata_ok,
        metadata_reason=metadata_reason,
        policy_trace_refs_ok=policy_ok,
        policy_trace_refs_reason=policy_reason,
    )


def verify_proof_bundle_file(path: str | Path) -> BundleVerificationResult:
    """Convenience: load a bundle from disk and verify it."""
    p = Path(path)
    try:
        bundle = json.loads(p.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise BundleVerificationError(f"bundle file not found: {p}") from exc
    except json.JSONDecodeError as exc:
        raise BundleSchemaError(f"{p}: not valid JSON: {exc.msg}") from exc
    return verify_proof_bundle(bundle)


__all__ = [
    "BundleSchemaError",
    "BundleVerificationError",
    "BundleVerificationResult",
    "verify_proof_bundle",
    "verify_proof_bundle_file",
]
