# SPDX-FileCopyrightText: 2026 The Attestplane Authors
# SPDX-License-Identifier: Apache-2.0
"""High-level proof-bundle verifier.

Takes a bundle dict (or path to a bundle JSON file), validates against
``schemas/v1/proof_bundle.schema.json``, rehydrates the contained
events, re-walks the chain with :func:`~attestplane.hashchain.verify_chain`,
and returns a :class:`BundleVerificationResult`.

Verifiers are intentionally **pure** with respect to the bundle: they
do not mutate, sign, or anchor. Verification is read-only.
"""

from __future__ import annotations

import json
import re
import sys
from base64 import b64decode
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any, Literal

from attestplane.event_types import POLICY_CHECK_EVENT
from attestplane.hashchain import (
    GENESIS_HASH,
    SUPPORTED_SCHEMA_VERSIONS,
    VerificationResult,
    hash_event,
    head_of,
    verify_chain,
)
from attestplane.proof_bundle import DEFAULT_FORBIDDEN_FIELDS
from attestplane.retention import verify_retention_proofs
from attestplane.storage.jsonl import _deserialize_event as _deserialize_chained_event
from attestplane.types import ChainedEvent
from attestplane.verify_errors import (
    VERIFY_BUNDLE_SCHEMA_INCOMPLETE,
    VERIFY_CHAIN_RECOMPUTE_FAILED,
    VERIFY_METADATA_CLOSURE_FAILED,
    VERIFY_OK,
    VERIFY_POLICY_TRACE_REFS_FAILED,
    VERIFY_REQUIRED_FIELDS_MISSING,
    VERIFY_RETENTION_PROOF_FAILED,
    VerifyErrorCode,
)
from attestplane.verify_reason_codes import (
    VERIFY_REASON_CANONICAL_MISMATCH,
    VERIFY_REASON_REQUIRED_FIELD_MISSING,
    VERIFY_REASON_SCHEMA_INVALID,
    VERIFY_REASON_SCHEMA_UNKNOWN,
    VERIFY_REASON_SCHEMA_VERSION_MISSING,
    VERIFY_REASON_SCHEMA_VERSION_UNSUPPORTED,
    VERIFY_REASON_SIGNATURE_INVALID,
    VERIFY_REASON_SIGNATURE_MISSING,
    VERIFY_REASON_STRUCTURE_INVALID,
    VerifyReasonCodeV1,
)


class BundleVerificationError(Exception):
    """Base class for verifier failures that are NOT chain integrity failures.

    Chain-integrity failures are reported via
    :class:`BundleVerificationResult` (``ok=False``); this exception is
    reserved for malformed inputs that prevent verification from running
    at all (bad JSON, schema violation, unreadable file).
    """


class BundleSchemaError(BundleVerificationError):
    """The bundle JSON does not conform to proof_bundle.schema.json."""


@dataclass(frozen=True, slots=True)
class BundleVerificationResult:
    """Outcome of verifying a proof bundle.

    - ``ok=True`` means the embedded chain verifies AND the bundle's own
      ``verification_report.ok`` agreed.
    - ``ok=False`` means EITHER the bundle's report disagrees with our
      independent re-verification, OR our re-verification surfaced a
      chain integrity failure.

    A disagreement between the embedded report and the independent
    re-verification is a strong signal: it means the bundle was either
    generated by a buggy producer or has been tampered with between
    generation and reading.

    The ``anchoring_status`` and ``quarantine_reason`` fields are
    additive advisory metadata. Callers may ignore them if they do not
    participate in anchoring policy enforcement.
    """

    ok: bool
    chain_result: VerificationResult
    bundle_reported_ok: bool
    agreement: bool
    """``True`` iff the bundle's embedded report agrees with the independent re-verification."""
    event_count: int
    bundle_version: int
    chain_id: str
    head_hash_hex: str
    metadata_ok: bool
    metadata_reason: str | None
    policy_trace_refs_ok: bool
    policy_trace_refs_reason: str | None
    retention_proofs_ok: bool
    retention_proofs_reason: str | None
    signed_attestation_schema_ok: bool
    signed_attestation_schema_reason: str | None
    anchoring_status: Literal["verified", "quarantined", "absent"]
    quarantine_reason: str | None
    error_code: VerifyErrorCode
    primary_reason: VerifyReasonCodeV1 | None
    secondary_reasons: tuple[VerifyReasonCodeV1, ...]

    def short_summary(self) -> str:
        if self.ok:
            summary = f"OK chain_id={self.chain_id!r} events={self.event_count} head={self.head_hash_hex[:16]}…"
            if self.anchoring_status != "absent":
                summary = f"{summary} anchoring_status={self.anchoring_status}"
                if self.anchoring_status == "quarantined" and self.quarantine_reason:
                    summary = f"{summary} quarantine_reason={self.quarantine_reason}"
            return summary
        bad = self.chain_result.first_bad_index
        return (
            f"FAIL chain_id={self.chain_id!r} events={self.event_count} "
            f"first_bad_index={bad} reason={self.chain_result.reason!r} "
            f"agreement={self.agreement} metadata_reason={self.metadata_reason!r} "
            f"policy_trace_refs_reason={self.policy_trace_refs_reason!r} "
            f"retention_proofs_reason={self.retention_proofs_reason!r} "
            f"signed_attestation_schema_reason={self.signed_attestation_schema_reason!r} "
            f"anchoring_status={self.anchoring_status!r} "
            f"quarantine_reason={self.quarantine_reason!r} "
            f"error_code={self.error_code} primary_reason={self.primary_reason}"
        )


_REQUIRED_TOP_LEVEL = {
    "bundle_version",
    "chain_metadata",
    "events",
    "verification_report",
    "forbidden_fields",
}
_REQUIRED_CHAIN_METADATA = {
    "chain_id",
    "genesis_hash_hex",
    "head_hash_hex",
    "head_seq",
    "producer_runtime",
}
_REQUIRED_VERIFICATION_REPORT = {
    "ok",
    "first_bad_index",
    "reason",
    "verified_at",
    "verifier_version",
    "verification_method",
}
_ALLOWED_TOP_LEVEL = _REQUIRED_TOP_LEVEL | {
    "framework_mappings",
    "signature",
    "policy_trace_refs",
    "signatures",
    "retention_proofs",
}
_FAIL_CLOSED_UNKNOWN_TOP_LEVEL_FIELDS = {"proof_type"}
_ALLOWED_VERIFICATION_METHODS = {"canonical-bytes-walk", "canonical-bytes-walk+anchor"}
_HEX64 = re.compile(r"^[0-9a-f]{64}$")
_ANCHORING_STATUSES = {"verified", "quarantined", "absent"}


def _validate_shape(bundle: Any) -> None:
    """Lightweight schema validation — sufficient to safely rehydrate.

    Intentionally not the full JSON Schema validator. Callers who need
    the full validator can run ``jsonschema.validate(bundle, schema)``
    against ``schemas/v1/proof_bundle.schema.json``; for the verifier
    fast path we only check what we read.
    """
    if not isinstance(bundle, dict):
        raise BundleSchemaError(f"bundle must be a JSON object, got {type(bundle).__name__}")
    missing = _REQUIRED_TOP_LEVEL - set(bundle)
    if missing:
        raise BundleSchemaError(f"bundle missing required fields: {sorted(missing)}")
    fail_closed_unknown_fields = sorted(
        key
        for key in set(bundle) - _ALLOWED_TOP_LEVEL
        if key in _FAIL_CLOSED_UNKNOWN_TOP_LEVEL_FIELDS or key.startswith("critical_")
    )
    if fail_closed_unknown_fields:
        raise BundleSchemaError(f"unknown top-level fields: {fail_closed_unknown_fields}")
    if bundle["bundle_version"] != 1:
        raise BundleSchemaError(
            f"unsupported bundle_version={bundle['bundle_version']!r}; this verifier handles version 1 only"
        )
    if not isinstance(bundle["chain_metadata"], dict):
        raise BundleSchemaError("chain_metadata must be a JSON object")
    missing_cm = _REQUIRED_CHAIN_METADATA - set(bundle["chain_metadata"])
    if missing_cm:
        raise BundleSchemaError(f"chain_metadata missing required fields: {sorted(missing_cm)}")
    if not isinstance(bundle["events"], list):
        raise BundleSchemaError("events must be an array")
    if not isinstance(bundle["verification_report"], dict):
        raise BundleSchemaError("verification_report must be a JSON object")
    missing_report = _REQUIRED_VERIFICATION_REPORT - set(bundle["verification_report"])
    if missing_report:
        raise BundleSchemaError(f"verification_report missing required fields: {sorted(missing_report)}")
    method = bundle["verification_report"]["verification_method"]
    if method not in _ALLOWED_VERIFICATION_METHODS:
        raise BundleSchemaError(f"unsupported verification_method={method!r}")
    if not isinstance(bundle["forbidden_fields"], list):
        raise BundleSchemaError("forbidden_fields must be an array")
    forbidden = bundle["forbidden_fields"]
    if not all(isinstance(item, str) and item for item in forbidden):
        raise BundleSchemaError("forbidden_fields must contain non-empty strings")
    missing_forbidden = set(DEFAULT_FORBIDDEN_FIELDS) - set(forbidden)
    if missing_forbidden:
        raise BundleSchemaError(f"forbidden_fields missing required redaction terms: {sorted(missing_forbidden)}")
    if "framework_mappings" in bundle and not isinstance(bundle["framework_mappings"], list):
        raise BundleSchemaError("framework_mappings must be an array when present")
    if "policy_trace_refs" in bundle and not isinstance(bundle["policy_trace_refs"], list):
        raise BundleSchemaError("policy_trace_refs must be an array when present")
    if "retention_proofs" in bundle and not isinstance(bundle["retention_proofs"], list):
        raise BundleSchemaError("retention_proofs must be an array when present")


def _schema_version_reason(metadata: dict[str, Any]) -> VerifyReasonCodeV1 | None:
    if "schema_version" not in metadata:
        return VERIFY_REASON_SCHEMA_VERSION_MISSING
    schema_version = metadata["schema_version"]
    if not isinstance(schema_version, int):
        return VERIFY_REASON_SCHEMA_INVALID
    if schema_version not in SUPPORTED_SCHEMA_VERSIONS:
        return VERIFY_REASON_SCHEMA_VERSION_UNSUPPORTED
    return None


def _anchoring_state(bundle: dict[str, Any]) -> tuple[Literal["verified", "quarantined", "absent"], str | None]:
    """Derive the advisory anchoring state from additive bundle metadata."""
    anchoring = bundle.get("anchoring")
    if isinstance(anchoring, dict):
        quarantine = anchoring.get("quarantine")
        if isinstance(quarantine, dict):
            reason = quarantine.get("reason") or quarantine.get("message")
            if isinstance(reason, str) and reason:
                return "quarantined", reason
            return "quarantined", None
        if isinstance(quarantine, str) and quarantine:
            return "quarantined", quarantine
        status = anchoring.get("anchoring_status")
        if not isinstance(status, str):
            status = anchoring.get("status")
        if isinstance(status, str) and status in _ANCHORING_STATUSES:
            quarantine_reason = anchoring.get("quarantine_reason")
            if status == "quarantined":
                if isinstance(quarantine_reason, str) and quarantine_reason:
                    return "quarantined", quarantine_reason
                quarantine = anchoring.get("quarantine")
                if isinstance(quarantine, dict):
                    reason = quarantine.get("reason") or quarantine.get("message")
                    if isinstance(reason, str) and reason:
                        return "quarantined", reason
                if isinstance(quarantine, str) and quarantine:
                    return "quarantined", quarantine
                return "quarantined", None
            if status == "verified":
                return "verified", None
            return "absent", None
        quarantine_reason = anchoring.get("quarantine_reason")
        if isinstance(quarantine_reason, str) and quarantine_reason:
            return "quarantined", quarantine_reason
    chain_metadata = bundle.get("chain_metadata")
    if isinstance(chain_metadata, dict):
        anchor_ref = chain_metadata.get("anchor_ref")
        if isinstance(anchor_ref, str) and anchor_ref:
            return "verified", None
    return "absent", None


def _unknown_required_field_reason(
    section: dict[str, Any],
    *,
    section_name: str,
) -> str | None:
    critical_fields = sorted(key for key in section if key.startswith("critical_"))
    if not critical_fields:
        return None
    field = critical_fields[0]
    return f"{section_name}.{field} is an unknown required field"


def _rehydrate_events(events_raw: list[dict[str, Any]]) -> list[ChainedEvent]:
    chain: list[ChainedEvent] = []
    for idx, ev_raw in enumerate(events_raw):
        try:
            chain.append(_deserialize_chained_event(ev_raw))
        except (KeyError, ValueError, TypeError) as exc:
            raise BundleSchemaError(f"events[{idx}]: malformed event row: {exc}") from exc
    return chain


def _validate_minimum_signed_attestation_schema(
    bundle: dict[str, Any],
    events: list[ChainedEvent],
) -> tuple[bool, str | None]:
    """Require one syntactically valid signature over a canonical event digest.

    This is a pre-crypto schema gate: it proves the bundle contains at
    least one well-shaped ADR-0005 signature record whose subject digest
    matches a canonical event hash already present in the bundle. Trust-root
    lookup and Ed25519 verification remain outside this chain/report verifier.
    """
    if not events:
        return False, "events must contain at least one event before signed-attestation schema can pass"
    signatures = bundle.get("signatures")
    if not isinstance(signatures, list) or not signatures:
        return False, "signatures must contain at least one signed attestation"

    canonical_event_hashes = {hash_event(event.event).hex() for event in events}
    if len(canonical_event_hashes) != len(events):
        return False, "events do not have unique canonical subject digests"

    malformed_reasons: list[str] = []
    for index, raw in enumerate(signatures):
        if not isinstance(raw, dict):
            malformed_reasons.append(f"signatures[{index}] must be an object")
            continue
        digest = raw.get("signed_event_hash_hex")
        if not isinstance(digest, str) or not _HEX64.match(digest):
            malformed_reasons.append(f"signatures[{index}].signed_event_hash_hex must be lowercase 64-hex")
            continue
        if digest not in canonical_event_hashes:
            malformed_reasons.append(
                f"signatures[{index}].signed_event_hash_hex does not match a canonical bundle event"
            )
            continue
        shape_reason = _validate_signature_record_shape(raw, index)
        if shape_reason is not None:
            malformed_reasons.append(shape_reason)
            continue
        return True, None

    joined = "; ".join(malformed_reasons) if malformed_reasons else "no usable signature record"
    return False, joined


def _validate_signature_record_shape(raw: dict[str, Any], index: int) -> str | None:
    required = {
        "signature_schema_version",
        "signed_seq",
        "signed_event_hash_hex",
        "signature_hex",
        "key_id",
        "public_key_der_b64",
        "signing_cert_chain_b64",
        "signed_at",
        "signature_mode",
        "signed_payload_b64",
    }
    missing = sorted(required - set(raw))
    if missing:
        return f"signatures[{index}] is malformed: missing fields {missing}"
    if not isinstance(raw["signature_schema_version"], int) or raw["signature_schema_version"] < 1:
        return f"signatures[{index}].signature_schema_version must be a positive integer"
    if not isinstance(raw["signed_seq"], int) or raw["signed_seq"] < 0:
        return f"signatures[{index}].signed_seq must be a non-negative integer"
    if not isinstance(raw["signature_hex"], str) or not re.fullmatch(r"[0-9a-f]{128}", raw["signature_hex"]):
        return f"signatures[{index}] is malformed: signature_hex must be lowercase 128-hex"
    if not isinstance(raw["key_id"], str) or not re.fullmatch(r"[0-9a-f]{32}", raw["key_id"]):
        return f"signatures[{index}].key_id must be lowercase 32-hex"
    if raw["signature_mode"] not in {"segment_head", "per_event"}:
        return f"signatures[{index}].signature_mode must be segment_head or per_event"
    reason = _decode_b64_field(raw, "public_key_der_b64", index)
    if reason is not None:
        return reason
    reason = _decode_b64_field(raw, "signed_payload_b64", index)
    if reason is not None:
        return reason
    cert_chain = raw["signing_cert_chain_b64"]
    if not isinstance(cert_chain, list):
        return f"signatures[{index}].signing_cert_chain_b64 must be a list"
    for cert_index, cert in enumerate(cert_chain):
        if not isinstance(cert, str):
            return f"signatures[{index}].signing_cert_chain_b64[{cert_index}] must be a string"
        try:
            b64decode(cert, validate=True)
        except Exception:
            return f"signatures[{index}].signing_cert_chain_b64[{cert_index}] must be base64"
    signed_at = raw["signed_at"]
    if not isinstance(signed_at, str):
        return f"signatures[{index}].signed_at must be a string"
    try:
        if signed_at.endswith("Z"):
            datetime.fromisoformat(signed_at.removesuffix("Z") + "+00:00")
        else:
            datetime.fromisoformat(signed_at)
    except ValueError:
        return f"signatures[{index}].signed_at must be RFC3339/ISO-8601 datetime text"
    return None


def _decode_b64_field(raw: dict[str, Any], field: str, index: int) -> str | None:
    value = raw[field]
    if not isinstance(value, str):
        return f"signatures[{index}].{field} must be a string"
    try:
        b64decode(value, validate=True)
    except Exception:
        return f"signatures[{index}].{field} must be base64"
    return None


def _signed_attestation_reason_code(reason: str | None) -> VerifyReasonCodeV1:
    if reason is None:
        return VERIFY_REASON_SIGNATURE_INVALID
    if reason.startswith("events must contain"):
        return VERIFY_REASON_REQUIRED_FIELD_MISSING
    if reason.startswith("signatures must contain"):
        return VERIFY_REASON_SIGNATURE_MISSING
    if "missing fields" in reason or "signed_event_hash_hex must" in reason:
        return VERIFY_REASON_REQUIRED_FIELD_MISSING
    return VERIFY_REASON_SIGNATURE_INVALID


def classify_bundle_schema_error(exc: BaseException | str) -> VerifyReasonCodeV1:
    """Map local schema failures to stable public verifier reason codes."""
    text = str(exc)
    if "unsupported bundle_version" in text:
        return VERIFY_REASON_SCHEMA_VERSION_UNSUPPORTED
    if "unsupported verification_method" in text:
        return VERIFY_REASON_SCHEMA_UNKNOWN
    if "missing required fields" in text or "missing fields" in text:
        return VERIFY_REASON_REQUIRED_FIELD_MISSING
    if "must be a JSON object" in text or "must be an array" in text:
        return VERIFY_REASON_SCHEMA_INVALID
    if "unknown top-level fields" in text:
        return VERIFY_REASON_SCHEMA_UNKNOWN
    if "schema_version" in text and "handles" in text:
        return VERIFY_REASON_SCHEMA_VERSION_UNSUPPORTED
    return VERIFY_REASON_SCHEMA_INVALID


def _dedupe_reasons(
    reasons: list[VerifyReasonCodeV1],
) -> tuple[VerifyReasonCodeV1 | None, tuple[VerifyReasonCodeV1, ...]]:
    seen: set[VerifyReasonCodeV1] = set()
    ordered: list[VerifyReasonCodeV1] = []
    for reason in reasons:
        if reason not in seen:
            seen.add(reason)
            ordered.append(reason)
    if not ordered:
        return None, ()
    return ordered[0], tuple(ordered[1:])


def _schema_version_reason_code(metadata_reason: str | None) -> VerifyReasonCodeV1 | None:
    if metadata_reason is None:
        return None
    if metadata_reason == "chain_metadata.schema_version is missing":
        return VERIFY_REASON_SCHEMA_VERSION_MISSING
    if metadata_reason == "chain_metadata.schema_version must be an integer":
        return VERIFY_REASON_SCHEMA_INVALID
    if metadata_reason.startswith("chain_metadata.schema_version="):
        return VERIFY_REASON_SCHEMA_VERSION_UNSUPPORTED
    if "unknown required field" in metadata_reason:
        return VERIFY_REASON_SCHEMA_UNKNOWN
    return None


def _verification_reasons(
    *,
    chain_result: VerificationResult,
    agreement: bool,
    require_non_empty: bool,
    events: list[ChainedEvent],
    signed_schema_ok: bool,
    signed_schema_reason: str | None,
    metadata_ok: bool,
    metadata_reason: str | None,
    policy_ok: bool,
    retention_ok: bool,
) -> tuple[VerifyReasonCodeV1 | None, tuple[VerifyReasonCodeV1, ...]]:
    reasons: list[VerifyReasonCodeV1] = []
    if not chain_result.ok or not agreement:
        reasons.append(VERIFY_REASON_CANONICAL_MISMATCH)
    if require_non_empty and not events:
        reasons.append(VERIFY_REASON_REQUIRED_FIELD_MISSING)
    if not signed_schema_ok:
        reasons.append(_signed_attestation_reason_code(signed_schema_reason))
    if not metadata_ok:
        schema_version_reason = _schema_version_reason_code(metadata_reason)
        if schema_version_reason is not None:
            reasons.append(schema_version_reason)
        else:
            reasons.append(VERIFY_REASON_STRUCTURE_INVALID)
    if not policy_ok:
        reasons.append(VERIFY_REASON_STRUCTURE_INVALID)
    if not retention_ok:
        reasons.append(VERIFY_REASON_STRUCTURE_INVALID)
    return _dedupe_reasons(reasons)


def _verify_metadata_closure(
    bundle: dict[str, Any],
    events: list[ChainedEvent],
    chain_result: VerificationResult,
    *,
    require_non_empty: bool = False,
) -> tuple[bool, str | None]:
    metadata = bundle["chain_metadata"]
    report = bundle["verification_report"]
    if require_non_empty and not events:
        return False, "events must contain at least one event when require_non_empty=True"
    schema_reason = _schema_version_reason(metadata)
    if schema_reason is not None:
        if schema_reason is VERIFY_REASON_SCHEMA_VERSION_MISSING:
            return False, "chain_metadata.schema_version is missing"
        if schema_reason is VERIFY_REASON_SCHEMA_INVALID:
            return False, "chain_metadata.schema_version must be an integer"
        return False, (
            f"chain_metadata.schema_version={metadata.get('schema_version')!r}; "
            f"this verifier handles schema_version values {SUPPORTED_SCHEMA_VERSIONS}"
        )
    unknown_required_field = _unknown_required_field_reason(metadata, section_name="chain_metadata")
    if unknown_required_field is not None:
        return False, unknown_required_field
    report_unknown_required_field = _unknown_required_field_reason(
        report,
        section_name="verification_report",
    )
    if report_unknown_required_field is not None:
        return False, report_unknown_required_field
    if metadata["genesis_hash_hex"] != GENESIS_HASH.hex():
        return False, "chain_metadata.genesis_hash_hex does not match substrate genesis hash"
    if "evidence_taxonomy_version" in metadata and metadata["evidence_taxonomy_version"] != 1:
        return False, "chain_metadata.evidence_taxonomy_version must be 1 when present"

    head = head_of(events)
    if metadata["head_seq"] != head.seq:
        return False, (f"chain_metadata.head_seq={metadata['head_seq']!r} does not match computed head seq {head.seq}")
    if metadata["head_hash_hex"] != head.event_hash.hex():
        return False, "chain_metadata.head_hash_hex does not match computed chain head"

    if bool(report["ok"]) != chain_result.ok:
        return False, "verification_report.ok disagrees with recomputed chain result"
    if report["first_bad_index"] != chain_result.first_bad_index:
        return False, "verification_report.first_bad_index disagrees with recomputed chain result"
    if report["reason"] != chain_result.reason:
        return False, "verification_report.reason disagrees with recomputed chain result"
    if chain_result.ok and (report["first_bad_index"] is not None or report["reason"] is not None):
        return False, "verification_report carries failure detail while recomputed chain is ok"
    return True, None


def _verify_policy_trace_refs(bundle: dict[str, Any], events: list[ChainedEvent]) -> tuple[bool, str | None]:
    expected = [event.event_hash.hex() for event in events if event.event.event_type == POLICY_CHECK_EVENT]
    present = "policy_trace_refs" in bundle
    if not expected:
        if not present:
            return True, None
        refs = bundle["policy_trace_refs"]
        if refs == []:
            return False, "policy_trace_refs must be absent, not empty, when no policy_check_event exists"
        return False, "policy_trace_refs present but bundle contains no policy_check_event"

    if not present:
        return False, "policy_trace_refs missing while bundle contains policy_check_event"
    refs = bundle["policy_trace_refs"]
    if not all(isinstance(ref, str) and _HEX64.match(ref) for ref in refs):
        return False, "policy_trace_refs must contain only lowercase 64-hex event hashes"
    if len(refs) != len(set(refs)):
        return False, "policy_trace_refs contains duplicate event hashes"
    actual_event_hashes = {event.event_hash.hex() for event in events}
    dangling = [ref for ref in refs if ref not in actual_event_hashes]
    if dangling:
        return False, f"policy_trace_refs contains dangling refs: {dangling}"
    wrong_type = [ref for ref in refs if ref in actual_event_hashes and ref not in expected]
    if wrong_type:
        return False, f"policy_trace_refs points at non-policy events: {wrong_type}"
    if refs != expected:
        return False, "policy_trace_refs does not match chain-seq-ordered policy_check_event hashes"
    return True, None


def verify_proof_bundle(
    bundle: dict[str, Any],
    *,
    require_non_empty: bool = False,
    require_signed_attestation: bool = False,
) -> BundleVerificationResult:
    """Verify a parsed proof-bundle dict.

    Raises :class:`BundleSchemaError` if the shape is invalid. Otherwise
    returns a :class:`BundleVerificationResult`; ``result.ok`` is
    ``True`` only if the chain re-verifies AND the embedded report
    agreed. Set ``require_non_empty=True`` for audit/regulatory workflows
    where an empty-but-well-formed bundle should fail closed.
    """
    _validate_shape(bundle)
    events = _rehydrate_events(bundle["events"])
    effective_require_signed_attestation = require_signed_attestation or require_non_empty
    if effective_require_signed_attestation:
        signed_schema_ok, signed_schema_reason = _validate_minimum_signed_attestation_schema(
            bundle,
            events,
        )
    else:
        signed_schema_ok, signed_schema_reason = True, None
    chain_result = verify_chain(events)
    bundle_reported_ok = bool(bundle["verification_report"]["ok"])
    agreement = bundle_reported_ok == chain_result.ok
    metadata_ok, metadata_reason = _verify_metadata_closure(
        bundle,
        events,
        chain_result,
        require_non_empty=require_non_empty,
    )
    policy_ok, policy_reason = _verify_policy_trace_refs(bundle, events)
    retention_result = verify_retention_proofs(
        bundle.get("retention_proofs"),
        {event.event_hash.hex() for event in events},
    )
    anchoring_status, quarantine_reason = _anchoring_state(bundle)
    error_code: VerifyErrorCode = VERIFY_OK
    if not chain_result.ok or not agreement:
        error_code = VERIFY_CHAIN_RECOMPUTE_FAILED
    elif require_non_empty and not events:
        error_code = VERIFY_REQUIRED_FIELDS_MISSING
    elif not signed_schema_ok:
        error_code = VERIFY_BUNDLE_SCHEMA_INCOMPLETE
    elif not metadata_ok:
        error_code = VERIFY_METADATA_CLOSURE_FAILED
    elif not policy_ok:
        error_code = VERIFY_POLICY_TRACE_REFS_FAILED
    elif not retention_result.ok:
        error_code = VERIFY_RETENTION_PROOF_FAILED
    primary_reason, secondary_reasons = _verification_reasons(
        chain_result=chain_result,
        agreement=agreement,
        require_non_empty=require_non_empty,
        events=events,
        signed_schema_ok=signed_schema_ok,
        signed_schema_reason=signed_schema_reason,
        metadata_ok=metadata_ok,
        metadata_reason=metadata_reason,
        policy_ok=policy_ok,
        retention_ok=retention_result.ok,
    )
    return BundleVerificationResult(
        ok=(chain_result.ok and agreement and metadata_ok and policy_ok and retention_result.ok and signed_schema_ok),
        chain_result=chain_result,
        bundle_reported_ok=bundle_reported_ok,
        agreement=agreement,
        event_count=len(events),
        bundle_version=int(bundle["bundle_version"]),
        chain_id=str(bundle["chain_metadata"]["chain_id"]),
        head_hash_hex=str(bundle["chain_metadata"]["head_hash_hex"]),
        metadata_ok=metadata_ok,
        metadata_reason=metadata_reason,
        policy_trace_refs_ok=policy_ok,
        policy_trace_refs_reason=policy_reason,
        retention_proofs_ok=retention_result.ok,
        retention_proofs_reason=retention_result.reason,
        signed_attestation_schema_ok=signed_schema_ok,
        signed_attestation_schema_reason=signed_schema_reason,
        anchoring_status=anchoring_status,
        quarantine_reason=quarantine_reason,
        error_code=error_code,
        primary_reason=primary_reason,
        secondary_reasons=secondary_reasons,
    )


def verify_proof_bundle_file(
    path: str | Path,
    *,
    require_non_empty: bool = False,
    require_signed_attestation: bool = False,
) -> BundleVerificationResult:
    """Convenience: load a bundle from disk and verify it."""
    p = Path(path)
    try:
        bundle = json.loads(p.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise BundleVerificationError(f"bundle file not found: {p}") from exc
    except json.JSONDecodeError as exc:
        raise BundleSchemaError(f"{p}: not valid JSON: {exc.msg}") from exc
    return verify_proof_bundle(
        bundle,
        require_non_empty=require_non_empty,
        require_signed_attestation=require_signed_attestation,
    )


def main(argv: list[str] | None = None) -> int:
    """Small module entrypoint for ``python -m attestplane.verifier``.

    Reads one JSON bundle from stdin. ``--strict`` applies the minimum signed
    proof-bundle contract used by SDK examples and conformance vectors.
    """
    args = list(sys.argv[1:] if argv is None else argv)
    strict = False
    if args == ["--strict"]:
        strict = True
    elif args:
        sys.stderr.write("usage: python -m attestplane.verifier [--strict]\n")
        return 2

    try:
        raw = sys.stdin.read()
        bundle = json.loads(raw)
        result = verify_proof_bundle(
            bundle,
            require_non_empty=strict,
            require_signed_attestation=strict,
        )
    except (BundleVerificationError, json.JSONDecodeError) as exc:
        sys.stderr.write(f"FAIL: {exc}\n")
        return 2

    if result.ok:
        sys.stdout.write(result.short_summary() + "\n")
        return 0
    sys.stderr.write(result.short_summary() + "\n")
    return 2


__all__ = [
    "BundleSchemaError",
    "BundleVerificationError",
    "BundleVerificationResult",
    "classify_bundle_schema_error",
    "verify_proof_bundle",
    "verify_proof_bundle_file",
]


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
