# SPDX-FileCopyrightText: 2026 The Attestplane Authors
# SPDX-License-Identifier: Apache-2.0
"""High-level proof-bundle verifier.

Takes a bundle dict (or path to a bundle JSON file), validates against
``schemas/v1/proof_bundle.schema.json``, rehydrates the contained
events, re-walks the chain with :func:`~attestplane.hashchain.verify_chain`,
and returns a :class:`BundleVerificationResult`.

Verifiers are intentionally **pure** with respect to the bundle: they
do not mutate, sign, or anchor. Verification is read-only.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from attestplane.hashchain import VerificationResult, verify_chain
from attestplane.storage.jsonl import _deserialize_event as _deserialize_chained_event
from attestplane.types import ChainedEvent


class BundleVerificationError(Exception):
    """Base class for verifier failures that are NOT chain integrity failures.

    Chain-integrity failures are reported via
    :class:`BundleVerificationResult` (``ok=False``); this exception is
    reserved for malformed inputs that prevent verification from running
    at all (bad JSON, schema violation, unreadable file).
    """


class BundleSchemaError(BundleVerificationError):
    """The bundle JSON does not conform to proof_bundle.schema.json."""


@dataclass(frozen=True, slots=True)
class BundleVerificationResult:
    """Outcome of verifying a proof bundle.

    - ``ok=True`` means the embedded chain verifies AND the bundle's own
      ``verification_report.ok`` agreed.
    - ``ok=False`` means EITHER the bundle's report disagrees with our
      independent re-verification, OR our re-verification surfaced a
      chain integrity failure.

    A disagreement between the embedded report and the independent
    re-verification is a strong signal: it means the bundle was either
    generated by a buggy producer or has been tampered with between
    generation and reading.
    """

    ok: bool
    chain_result: VerificationResult
    bundle_reported_ok: bool
    agreement: bool
    """``True`` iff the bundle's embedded report agrees with the independent re-verification."""
    event_count: int
    bundle_version: int
    chain_id: str
    head_hash_hex: str

    def short_summary(self) -> str:
        if self.ok:
            return (
                f"OK chain_id={self.chain_id!r} events={self.event_count} "
                f"head={self.head_hash_hex[:16]}…"
            )
        bad = self.chain_result.first_bad_index
        return (
            f"FAIL chain_id={self.chain_id!r} events={self.event_count} "
            f"first_bad_index={bad} reason={self.chain_result.reason!r} "
            f"agreement={self.agreement}"
        )


_REQUIRED_TOP_LEVEL = {
    "bundle_version",
    "chain_metadata",
    "events",
    "verification_report",
    "forbidden_fields",
}
_REQUIRED_CHAIN_METADATA = {
    "chain_id", "schema_version", "genesis_hash_hex",
    "head_hash_hex", "head_seq", "producer_runtime",
}


def _validate_shape(bundle: Any) -> None:
    """Lightweight schema validation — sufficient to safely rehydrate.

    Intentionally not the full JSON Schema validator. Callers who need
    the full validator can run ``jsonschema.validate(bundle, schema)``
    against ``schemas/v1/proof_bundle.schema.json``; for the verifier
    fast path we only check what we read.
    """
    if not isinstance(bundle, dict):
        raise BundleSchemaError(f"bundle must be a JSON object, got {type(bundle).__name__}")
    missing = _REQUIRED_TOP_LEVEL - set(bundle)
    if missing:
        raise BundleSchemaError(f"bundle missing required fields: {sorted(missing)}")
    if bundle["bundle_version"] != 1:
        raise BundleSchemaError(
            f"unsupported bundle_version={bundle['bundle_version']!r}; "
            f"this verifier handles version 1 only"
        )
    if not isinstance(bundle["chain_metadata"], dict):
        raise BundleSchemaError("chain_metadata must be a JSON object")
    missing_cm = _REQUIRED_CHAIN_METADATA - set(bundle["chain_metadata"])
    if missing_cm:
        raise BundleSchemaError(
            f"chain_metadata missing required fields: {sorted(missing_cm)}"
        )
    if not isinstance(bundle["events"], list):
        raise BundleSchemaError("events must be an array")
    if not isinstance(bundle["verification_report"], dict):
        raise BundleSchemaError("verification_report must be a JSON object")
    if not isinstance(bundle["forbidden_fields"], list):
        raise BundleSchemaError("forbidden_fields must be an array")


def _rehydrate_events(events_raw: list[dict[str, Any]]) -> list[ChainedEvent]:
    chain: list[ChainedEvent] = []
    for idx, ev_raw in enumerate(events_raw):
        try:
            chain.append(_deserialize_chained_event(ev_raw))
        except (KeyError, ValueError, TypeError) as exc:
            raise BundleSchemaError(
                f"events[{idx}]: malformed event row: {exc}"
            ) from exc
    return chain


def verify_proof_bundle(bundle: dict[str, Any]) -> BundleVerificationResult:
    """Verify a parsed proof-bundle dict.

    Raises :class:`BundleSchemaError` if the shape is invalid. Otherwise
    returns a :class:`BundleVerificationResult`; ``result.ok`` is
    ``True`` only if the chain re-verifies AND the embedded report
    agreed.
    """
    _validate_shape(bundle)
    events = _rehydrate_events(bundle["events"])
    chain_result = verify_chain(events)
    bundle_reported_ok = bool(bundle["verification_report"]["ok"])
    agreement = bundle_reported_ok == chain_result.ok
    return BundleVerificationResult(
        ok=chain_result.ok and agreement,
        chain_result=chain_result,
        bundle_reported_ok=bundle_reported_ok,
        agreement=agreement,
        event_count=len(events),
        bundle_version=int(bundle["bundle_version"]),
        chain_id=str(bundle["chain_metadata"]["chain_id"]),
        head_hash_hex=str(bundle["chain_metadata"]["head_hash_hex"]),
    )


def verify_proof_bundle_file(path: str | Path) -> BundleVerificationResult:
    """Convenience: load a bundle from disk and verify it."""
    p = Path(path)
    try:
        bundle = json.loads(p.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise BundleVerificationError(f"bundle file not found: {p}") from exc
    except json.JSONDecodeError as exc:
        raise BundleSchemaError(f"{p}: not valid JSON: {exc.msg}") from exc
    return verify_proof_bundle(bundle)


__all__ = [
    "BundleSchemaError",
    "BundleVerificationError",
    "BundleVerificationResult",
    "verify_proof_bundle",
    "verify_proof_bundle_file",
]
