# SPDX-FileCopyrightText: 2026 The Attestplane Authors
# SPDX-License-Identifier: Apache-2.0
"""Concrete :class:`KeyProvider` implementations per architect plan § 1 D.

Ticket **T2** of `docs/architecture/adr_0005_signing_plan_20260517.md`.

Four providers:

- :class:`InMemoryKeyProvider` — tests / dev; optional 32-byte seed
  for deterministic keys, otherwise random.
- :class:`FileKeyProvider` — PKCS#8 PEM file on disk, optional
  passphrase.
- :class:`EnvKeyProvider` — PKCS#8 PEM bytes from an environment
  variable. Common deployment pattern when keys are injected via
  a secret manager.
- :class:`MultiSignerProvider` — plurality (any-of-n) composite per
  architect plan § 1 H. Mirrors
  :class:`~attestplane.anchoring.MultiTSAProvider`.

All four providers inherit the
:class:`~attestplane.signing.KeyProvider` forbidden-verb gate; any
subclass attempting to declare ``revoke`` / ``rotate`` / ``delete`` /
``replace`` is rejected at class-creation time.
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Final

try:
    from cryptography.hazmat.primitives import serialization
    from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
except ImportError as exc:  # pragma: no cover
    raise ImportError(
        "attestplane.signing.providers requires the 'signing' extras. "
        "Install with: pip install attestplane[signing]"
    ) from exc

from attestplane.signing.base import (
    SIGNATURE_SCHEMA_VERSION,
    KeyProvider,
    KeyProviderError,
    SigningMaterial,
)


_ED25519_SEED_LEN: Final[int] = 32


class InMemoryKeyProvider(KeyProvider):
    """Holds an Ed25519 keypair in process memory.

    Suitable for tests, ephemeral substrates, and deployments where
    the key is generated at startup and never persisted.

    :param seed: optional 32-byte deterministic seed. When provided,
        the same seed always produces the same Ed25519 key — useful
        for conformance vectors. When ``None``, a fresh random key
        is generated by :class:`cryptography`'s default RNG.
    :param provider_id: identifier embedded in the
        :class:`~attestplane.signing.SignatureRecord` chain via
        ``public_key_der``-derived ``key_id``.
    """

    schema_version = SIGNATURE_SCHEMA_VERSION

    def __init__(
        self,
        *,
        seed: bytes | None = None,
        provider_id: str = "in-memory",
    ) -> None:
        if not provider_id:
            raise ValueError("InMemoryKeyProvider provider_id must be non-empty")
        if seed is not None:
            if len(seed) != _ED25519_SEED_LEN:
                raise KeyProviderError(
                    f"InMemoryKeyProvider seed must be exactly {_ED25519_SEED_LEN} "
                    f"bytes, got {len(seed)}"
                )
            self._private_key = Ed25519PrivateKey.from_private_bytes(seed)
        else:
            self._private_key = Ed25519PrivateKey.generate()
        self.provider_id = provider_id

    def get_signing_material(self) -> SigningMaterial:
        return SigningMaterial(private_key=self._private_key)


class FileKeyProvider(KeyProvider):
    """Loads an Ed25519 private key from a PKCS#8 PEM file on disk.

    The file is read on **every** :meth:`get_signing_material` call;
    callers that want to amortise the read should wrap this in a
    process-local cache. The intentional design: file rotation
    (deployer replaces the file out-of-band) is picked up on the next
    signing call, without restarting the substrate.

    :param path: filesystem path to the PEM-encoded PKCS#8 key.
    :param passphrase: optional passphrase if the PEM is encrypted.
    :param provider_id: identifier (default: ``"file:<path>"``).
    """

    schema_version = SIGNATURE_SCHEMA_VERSION

    def __init__(
        self,
        path: str | os.PathLike[str],
        *,
        passphrase: bytes | None = None,
        provider_id: str | None = None,
    ) -> None:
        self._path = Path(path)
        self._passphrase = passphrase
        self.provider_id = provider_id or f"file:{self._path}"

    def get_signing_material(self) -> SigningMaterial:
        try:
            pem_bytes = self._path.read_bytes()
        except FileNotFoundError as exc:
            raise KeyProviderError(
                f"FileKeyProvider: key file not found at {self._path}"
            ) from exc
        except OSError as exc:
            raise KeyProviderError(
                f"FileKeyProvider: cannot read {self._path}: {exc}"
            ) from exc

        try:
            key = serialization.load_pem_private_key(
                pem_bytes, password=self._passphrase,
            )
        except Exception as exc:
            raise KeyProviderError(
                f"FileKeyProvider: failed to load PEM key from {self._path}: {exc}"
            ) from exc

        if not isinstance(key, Ed25519PrivateKey):
            raise KeyProviderError(
                f"FileKeyProvider: key at {self._path} is not Ed25519 "
                f"(got {type(key).__name__})"
            )
        return SigningMaterial(private_key=key)


class EnvKeyProvider(KeyProvider):
    """Loads an Ed25519 private key from an environment variable.

    The env var must contain a PEM-encoded PKCS#8 key (typical when
    the key is delivered by a secret manager).

    :param env_var: name of the environment variable holding the PEM
        bytes (string, not the bytes themselves).
    :param passphrase: optional passphrase if the PEM is encrypted.
    :param provider_id: identifier (default: ``"env:<env_var>"``).
    """

    schema_version = SIGNATURE_SCHEMA_VERSION

    def __init__(
        self,
        env_var: str,
        *,
        passphrase: bytes | None = None,
        provider_id: str | None = None,
    ) -> None:
        if not env_var:
            raise ValueError("EnvKeyProvider env_var must be non-empty")
        self._env_var = env_var
        self._passphrase = passphrase
        self.provider_id = provider_id or f"env:{env_var}"

    def get_signing_material(self) -> SigningMaterial:
        pem_text = os.environ.get(self._env_var)
        if pem_text is None:
            raise KeyProviderError(
                f"EnvKeyProvider: env var {self._env_var!r} is not set"
            )
        if not pem_text.strip():
            raise KeyProviderError(
                f"EnvKeyProvider: env var {self._env_var!r} is empty"
            )
        try:
            key = serialization.load_pem_private_key(
                pem_text.encode("utf-8"), password=self._passphrase,
            )
        except Exception as exc:
            raise KeyProviderError(
                f"EnvKeyProvider: failed to load PEM key from "
                f"env {self._env_var!r}: {exc}"
            ) from exc
        if not isinstance(key, Ed25519PrivateKey):
            raise KeyProviderError(
                f"EnvKeyProvider: key from {self._env_var!r} is not Ed25519 "
                f"(got {type(key).__name__})"
            )
        return SigningMaterial(private_key=key)


class MultiSignerProvider:
    """Plurality (any-of-n) composite per architect plan § 1 H.

    Holds N :class:`KeyProvider` instances and exposes their signing
    materials as a list. The downstream :class:`Signer` (T3 ticket)
    iterates and produces one :class:`~attestplane.signing.SignatureRecord`
    per provider per signed event.

    :class:`MultiSignerProvider` is intentionally **not** a
    :class:`KeyProvider` subclass: a KeyProvider returns one
    :class:`SigningMaterial`; this composite returns a list. Conflating
    them forces callers to flatten — better to keep the type
    distinction explicit (same pattern as
    :class:`~attestplane.anchoring.MultiTSAProvider`).

    Verification semantics (Verifier T4): any valid signature from
    any trust-rooted ``key_id`` in the document counts as "segment
    signed". This is plurality, NOT k-of-n threshold. Threshold
    semantics are explicitly out-of-scope (architect plan § 1 H).
    """

    def __init__(self, providers: list[KeyProvider]) -> None:
        if not providers:
            raise ValueError("MultiSignerProvider requires at least one provider")
        seen_ids = {p.provider_id for p in providers}
        if len(seen_ids) != len(providers):
            raise ValueError(
                "MultiSignerProvider providers must have distinct provider_id values"
            )
        for p in providers:
            if p.schema_version != SIGNATURE_SCHEMA_VERSION:
                raise ValueError(
                    f"provider {p.provider_id!r} has schema_version="
                    f"{p.schema_version}; this composite handles only "
                    f"SIGNATURE_SCHEMA_VERSION={SIGNATURE_SCHEMA_VERSION}"
                )
        self._providers = list(providers)

    @property
    def provider_ids(self) -> tuple[str, ...]:
        return tuple(p.provider_id for p in self._providers)

    def get_signing_materials(self) -> list[SigningMaterial]:
        """Fan out and gather every provider's signing material."""
        return [p.get_signing_material() for p in self._providers]


__all__ = [
    "EnvKeyProvider",
    "FileKeyProvider",
    "InMemoryKeyProvider",
    "MultiSignerProvider",
]
